// Pruebas puras de lógica; no inicializan el robot, el GamePad, radio ni sensores.
control.assert(copilliLogic.limit(-120, -100, 100) == -100, "limita potencia negativa")
control.assert(copilliLogic.limit(140, 0, 100) == 100, "limita potencia positiva")
control.assert(copilliLogic.limit(0, 0, 100) == 0, "cero permanece en cero")
control.assert(copilliLogic.limit(NaN, -100, 100) == 0, "NaN no ordena movimiento")
control.assert(copilliLogic.angleBetween(150, 30, 0) == 150, "extremo invertido 0")
control.assert(copilliLogic.angleBetween(150, 30, 50) == 90, "interpolacion invertida")
control.assert(copilliLogic.angleBetween(150, 30, 100) == 30, "extremo invertido 100")
control.assert(copilliLogic.angleBetween(10, 170, 150) == 170, "porcentaje saturado")
control.assert(copilliLogic.normalizeAxis(512, 512, 100, false) == 0, "centro joystick")
control.assert(copilliLogic.normalizeAxis(610, 512, 100, false) == 0, "zona muerta")
control.assert(copilliLogic.normalizeAxis(1023, 512, 100, false) == 100, "extremo X positivo")
control.assert(copilliLogic.normalizeAxis(0, 512, 100, false) == -100, "extremo X negativo")
control.assert(copilliLogic.normalizeAxis(0, 512, 100, true) == 100, "eje Y invertido")
control.assert(copilliLogic.dominantDirection(80, 80) == copilli.DireccionJoystick.Derecha, "diagonal empatada favorece X")
control.assert(copilliLogic.dominantDirection(40, -90) == copilli.DireccionJoystick.Abajo, "gana eje dominante")
control.assert(copilliLogic.dominantDirection(0, 0) == copilli.DireccionJoystick.Centro, "joystick centrado")

let debounce = copilliLogic.debounceSample(true, false, 0, false)
control.assert(debounce % 2 == 0, "ignora primer rebote")
debounce = copilliLogic.debounceSample(true, true, Math.idiv(debounce, 8), false)
control.assert(debounce % 2 == 0, "ignora segundo rebote")
debounce = copilliLogic.debounceSample(true, true, Math.idiv(debounce, 8), false)
control.assert(debounce % 2 == 1 && debounce % 4 >= 2, "acepta una transicion estable")
debounce = copilliLogic.debounceSample(true, true, Math.idiv(debounce, 8), true)
control.assert(debounce % 2 == 0, "mantener pulsado no repite transicion")
debounce = copilliLogic.debounceSample(false, true, Math.idiv(debounce, 8), true)
control.assert(debounce % 2 == 0, "primer muestreo de soltar no rebota")
debounce = copilliLogic.debounceSample(false, false, Math.idiv(debounce, 8), true)
control.assert(debounce % 2 == 0, "segundo muestreo de soltar no rebota")
debounce = copilliLogic.debounceSample(false, false, Math.idiv(debounce, 8), true)
control.assert(debounce % 2 == 1 && debounce % 4 < 2, "acepta una transicion estable al soltar")

// Doble de hardware: verifica órdenes sin energizar motores ni servos reales.
copilliHardware.enableTestDouble()
copilli.abrirPinza()
control.assert(copilliHardware.testServoCommandCount() == 0, "sin calibracion no ordena servo")
control.assert(!copilli.copilliRobotIsReady(), "Maqueen no se inicia al importar")
copilli.iniciarMaqueen()
control.assert(copilliHardware.testMotorCommandCount() == 2, "iniciar solo ordena detener ruedas")
copilli.iniciarMaqueen()
control.assert(copilliHardware.testMotorCommandCount() == 2, "inicializacion es idempotente")
copilli.avanzar(0)
control.assert(copilliHardware.testMotorSpeed(2) == 0 && copilliHardware.testMotorSpeed(3) == 0, "potencia cero detiene ambas ruedas")
copilli.moverRuedas(-200, 50)
control.assert(copilliHardware.testMotorWasLeft(4) && copilliHardware.testMotorDirection(4) == 1 &&
    copilliHardware.testMotorSpeed(4) == 255, "satura izquierda y respeta sentido")
control.assert(!copilliHardware.testMotorWasLeft(5) && copilliHardware.testMotorDirection(5) == 0 &&
    copilliHardware.testMotorSpeed(5) == 128, "escala derecha a 0-255")
copilli.detener()
control.assert(copilliHardware.testMotorSpeed(6) == 0 && copilliHardware.testMotorSpeed(7) == 0, "detener frena ambas ruedas")

// Sensores simulados: timeout es -1 y negro se identifica como nivel bajo.
copilliHardware.setFakeDistance(-1)
control.assert(copilli.distanciaCm() == -1, "timeout no equivale a camino despejado")
copilliHardware.setFakeDistance(22)
control.assert(copilli.distanciaCm() == 22, "distancia valida")
copilliHardware.setFakeLine(copilli.SensorLinea.Izquierdo, 0)
copilliHardware.setFakeLine(copilli.SensorLinea.Derecho, 1)
control.assert(copilli.sobreLinea(copilli.SensorLinea.Izquierdo), "linea negra izquierda")
control.assert(!copilli.sobreLinea(copilli.SensorLinea.Derecho), "fondo claro derecho")

// La configuración guarda datos sin emitir una orden; las acciones usan interpolación invertida.
copilli.configurarPinza(copilli.PuertoServo.S1, 30, 100)
control.assert(copilliHardware.testServoCommandCount() == 0, "configurar no mueve servo")
copilli.abrirPinza()
control.assert(copilliHardware.testServoAngle() == 30, "abrir usa extremo calibrado")
copilli.posicionMechanic(copilli.Mecanismo.Pinza, 50)
control.assert(copilliHardware.testServoAngle() == 65, "interpolacion semantica")
control.assert(copilliHardware.testServoPort() == copilli.PuertoServo.S1, "usa puerto asignado")
let servoCommandsBeforeInvalid = copilliHardware.testServoCommandCount()
copilli.configurarPinza(copilli.PuertoServo.S1, 0, 0)
control.assert(copilli.diagnostico().indexOf("rechazada") >= 0, "rechaza angulos invalidos")
copilli.posicionMechanic(copilli.Mecanismo.Pinza, NaN)
control.assert(copilliHardware.testServoCommandCount() == servoCommandsBeforeInvalid, "entrada invalida no ordena servo")
copilli.configurarPala(copilli.PuertoServo.S1, 120, 60)
control.assert(copilli.diagnostico().indexOf("otro mecanismo") >= 0, "rechaza conflicto de puerto")
copilli.quitarConfiguracionMechanic(copilli.PuertoServo.S1)
copilli.configurarPala(copilli.PuertoServo.S1, 120, 60)
control.assert(copilli.diagnostico() == "", "permite reasignar despues de quitar configuracion")
copilli.configurarSensorGiratorio(copilli.PuertoServo.S2, 40, 90, 140)
copilli.orientarSensor(copilli.DireccionSensor.Frente)
control.assert(copilliHardware.testServoPort() == copilli.PuertoServo.S2 &&
    copilliHardware.testServoAngle() == 90, "orienta Push con puerto calibrado")

// Sin iniciar, la API del mando no lee entradas ni arranca el sondeo.
control.assert(copilli.joystickX() == 0, "no lee GamePad sin inicializar")
control.assert(copilli.diagnostico().indexOf("iniciar GamePad") >= 0, "diagnostica GamePad no preparado")
